language: python
python:
  - "3.5"
sudo: false
before_install:
  - pip install coveralls
install:
  - pip install -r requirements.txt
script:
  python -m unittest discover
after_success:
    - coveralls