language: python
python:
  - "3.7"
sudo: false
before_install:
  - pip install coveralls pipenv
install:
  - pipenv install --deploy --ignore-pipfile --system --dev
script:
  nosetests --with-coverage --cover-package docker_enforcer,dockerenforcer
after_success:
  - coveralls
